### ISSUE TITLE
--disable-features. --enable-features flag triggering after update

### ISSUE THREAD

**Issue by Mipsters** [rcmaehl/MSEdgeRedirect#117]
**Check List**
- [x] Microsoft Edge is still installed (see issue 26)
- [x] Running `microsoft-edge:https://google.com` redirects successfully
- [ ] Reinstall or `/repair` was attempted for System Errors (see issues 25 & 77)
- [ ] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

**Install Type**
- [x] New Install
- [ ] New Deployment (winget/chocolatey/sccm)
- [ ] Update
- [ ] Managed Update (winget/chocolatey/sccm)

**Installed Mode**
- [x] Active Mode
- [ ] Service Mode
- [ ] Unsure

**Describe the bug**

After updating edge, trying to open it directly result in an error message:
![image](https://user-images.githubusercontent.com/4920832/161373429-ffd8075a-4439-4cb9-a1bb-31ce605168b8.png)
for searchability:
```
The code execution cannot proceed because C:\Program Files (x86)\Microsoft\Edfe\Application\99.0.1150.55\msedge_elf.dll was not found. Reinstalling the program may fix this problem
```

This happened to me over the last three edge updates
probably caused because the folder name change to the latest version name and MSEdge Redirect tries something with the old version?
opening MSEdge Redirect settings and saving (without changing anything) fixes this

**To Reproduce**
1. install MSEdgeRedirect
2. try to open Edge directly, see it succeeds
3. update Edge
4. try to open Edge directly, see an error message

**⚠️ File Upload ⚠️**
[edge.txt](https://github.com/rcmaehl/MSEdgeRedirect/files/8402095/edge.txt)

1. Leave edge open
2. Open Powershell
3. Run `gwmi Win32_Process | where { $_.name -like "msedge*.exe"} | Select-Object CommandLine | Format-Table -Wrap -AutoSize | Out-File $env:LOCALAPPDATA\MSEdgeRedirect\logs\edge.txt`
4. Open %localappdata%\MSEdgeRedirect\logs
5. Attach the log files

unrelated to the bug, the command above did not work for me, gwmi was not available
I used this instead:
```
Get-CimInstance -ClassName Win32_Process | where { $_.name -like "msedge*.exe"} | Select-Object CommandLine | Format-Table -Wrap -AutoSize | Out-File $env:LOCALAPPDATA\MSEdgeRedirect\logs\edge.txt
```

**Desktop (please complete the following information):**
 - Windows Version: 11
 - Windows Build: 22581.200

**Additional context**

**Comment by Neobond** [comment]
I have the same issue, a workaround is to run the installer again and choose Service mode and you will be able to open Edge again.

**Comment by Mipsters** [comment]
@Neobond you don't even need to install again, just open the settings and save them and it'll work
I mentioned this in the issue, but I forgot to specify that the settings needs to be opened 😅
After editing it says:
> opening MSEdge Redirect settings and saving (without changing anything) fixes this

**Comment by Neobond** [comment]
@Mipsters  I tried this, but it didn't work for me, I was about to uninstall it but decided to try the other option first.

**Comment by rcmaehl** [comment]
I'll have a fix for this by the end of the day

**Comment by Neobond** [comment]
Thanks!

**Comment by Neobond** [comment]
> I'll have a fix for this by the end of the day

This is what I got in Chrome address bar when I clicked on the Edge icon:

https://--disable-features%3Dmssidebarsearchforimageaftersearchwebfor%2Cmssidebarsearchforimagebeforesearchwebfor/

Hope it helps!

**Comment by rcmaehl** [comment]
Hi all!

This should be fixed now.

Please try the latest dev build:

**Comment by Neobond** [comment]
It's not fixed, I got the same thing, on trying to open Edge it opened a tab in Chrome instead

![SNAG-0024](https://user-images.githubusercontent.com/42996358/161400964-c10238b0-ea10-41ce-b4ef-9d88d7347d74.png)

**Comment by rcmaehl** [comment]
> It's not fixed, I got the same thing, on trying to open Edge it opened a tab in Chrome instead
> 
> ![SNAG-0024](https://user-images.githubusercontent.com/42996358/161400964-c10238b0-ea10-41ce-b4ef-9d88d7347d74.png)

Can you upload your log files?

**Comment by dtantono** [comment]
yeah me too and it is quite unstable

**Comment by Mipsters** [comment]
@rcmaehl hey, so I installed the latest version of MSEdgeResirect
probably because the install includes editing the settings, I could enter edge right after
I updated edge, and I still get the exact same error (but the path is of the current version, 100.0.1185.39)
the log files are empty when I run the command

**Comment by Mipsters** [comment]
when I try to run edge from the start menu, I get a different error
![image](https://user-images.githubusercontent.com/4920832/163706217-6845af09-9c72-43e2-a8e4-f2fa6dbf28e5.png)

I looked a bit into it
if I run edge from `C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe`
it doesn't work
if I run it directly from the current install
e.g.
`C:\Program Files (x86)\Microsoft\Edge\Application\100.0.1185.44\msedge.exe`
it does work, but behave oddly?
I get this in the updater
![image](https://user-images.githubusercontent.com/4920832/163706331-e11dadc1-9e7f-4a88-a950-49f966cac92d.png)
but that probably have something to do with running directly from the install directory

**Comment by rcmaehl** [comment]
I'll mess about with this later today then.

**Comment by rcmaehl** [comment]
> ![SNAG-0024](https://user-images.githubusercontent.com/42996358/161400964-c10238b0-ea10-41ce-b4ef-9d88d7347d74.png)

Still working on this one. The flag being passed is technically unsafe as it would allow an attacker to disable sandboxing and other security features.



>![image](https://user-images.githubusercontent.com/4920832/163706217-6845af09-9c72-43e2-a8e4-f2fa6dbf28e5.png)
> 
>![image](https://user-images.githubusercontent.com/4920832/163706331-e11dadc1-9e7f-4a88-a950-49f966cac92d.png) but that probably have something to do with running directly from the install directory

These are hopefully improved in the latest test build. I still have a bit of work to do.

https://nightly.link/rcmaehl/MSEdgeRedirect/workflows/MSER/main/mser.zip

**Comment by Neobond** [comment]
Apologies, I actually just disabled it and came back to update to version 0.6.5.0 today and it is all working as expected in Service Mode now. Tested with Chrome stable in Windows 10 22000.675 and Windows 11 build 25120 and even Windows 11 build 22621 because I was writing a guide on this https://www.neowin.net/news/force-widgets-in-windows-11-or-10-to-use-default-browser-instead-of-edge/

**Comment by rcmaehl** [comment]
> Apologies, I actually just disabled it and came back to update to version 0.6.5.0 today and it is all working as expected in Service Mode now. Tested with Chrome stable in Windows 10 22000.675 and Windows 11 build 25120 and even Windows 11 build 22621 because I was writing a guide on this https://www.neowin.net/news/force-widgets-in-windows-11-or-10-to-use-default-browser-instead-of-edge/
> 
> I am aSteveParker on Twitter Robert :)

Hi Steve,

Thanks for reviewing the software. If you have an issues or questions, feel free to reach out to me.

Regards, Robert

**Comment by Mipsters** [comment]
sorry for the far apart updates, I got dual boot in my laptop and usually use linux
I booted my windows and checked whats up
I updated MSER to the latest version and opened edge to update it and see if this still occurs
oddly edge was already up to date without me updating it, so I can't check the original bug ATM

but what I reported about running `msedge.exe` from the version directory and seeing this:
![](https://user-images.githubusercontent.com/4920832/163706331-e11dadc1-9e7f-4a88-a950-49f966cac92d.png)

still happen with MSER 0.6.5.0 and edge 102.0.1245.30

**Comment by Mipsters** [comment]
I uninstalled MSER and checked it, and the update error still occurs
so unless it changed something permanent in my computer, this probably isn't something that MSER causes

**Comment by Mipsters** [comment]
seems like this works now! I just updated edge and MSER worked great after!
and edge itself still works :)
