### ISSUE TITLE
Breaks Internet Explorer favorites / bookmarks on Windows 11

### ISSUE THREAD

**Issue by Axer128** [rcmaehl/MSEdgeRedirect#171]
### Preflight Checklist

- [X] Microsoft Edge is still installed (see issue 26)
- [X] Running microsoft-edge:https://google.com redirects successfully
- [X] Microsoft Edge is selected in any "How do you want to open this?" box (if applicable)

### Install Type

Manual Update

### Install Mode

Active Mode

### Steps to reproduce

Contrary to popular belief, Internet Explorer was not removed in windows 11. Running the verified clean iso directly downloaded from microsoft.com , 21H2, latest as of this reports time, is indeed included.
It is in fact installed by default , updated with security fixes and fully functional. Simply hidden by default. Just make a shortcut like this to open it:
"C:\Program Files\Internet Explorer\iexplore.exe" google.com/ -Embedding

This opens IE11, and searches for google.com in bing. Haven't figured out a way to default to google search permanently in it, M$ worked even harder to hard lock it to bing this time around. Even with all extensions disabled and changing the default search engine to google, it always opens in bing, and switches its search back to bing. (You can then use url bar and click google icon to switch it back to google, which makes google address bar searchs work normally for the session, but it won't remember this next launch)

Anyways, it fully works and for some ultra ancient work/super legacy stupid websites, still needed. As even edge's IEMode is not compatible with everything.

So yea reproduce:

1. Set up any bookmark as usual - I made one for google.com
2. Ctrl+shift+B to bring up the bookmarks bar.
3. Click bookmark.
4. MSEedgeRedirect flashes in system tray, and nothing happens.

Can also just click the star and pick your bookmark, same results.
If instead ctrl+B to bring up the favorites organizer, clicking them there does nothing, dragging them into the window does the same edgeredirect flash and nothing. Rclick and open, opens them in chrome, which is probably correct as they are actually just .url files, which my system is setup to open in chrome.

Lengthy workaround: rclick favorite, properties, copy the url. close, alt+d to address bar, ctrl+v paste it in. Works.

I also checked if my .url extension was messed in any way and nope it's 100% default windows 11 settings. Points to:
HKEY_CLASSES_ROOT\InternetShortcut\shell\Open\Command which points to:
"C:\Windows\System32\rundll32.exe" "C:\Windows\System32\ieframe.dll",OpenURL %l
Though also has the usual persistent handler screwery stuff windows does to make these also work as various protocol handlers/icon handlers.

I also have ran thru every step here to disable the IEtoEdge BHO:
https://www.winhelponline.com/blog/disable-auto-redirect-unsupported-sites-ie-to-edge/

So it doesn't try to redirect to edge in normal browsing anymore, nor have any edge icons anywhere. So even URLs that are usually forced to edge like most of microsoft.com, work fine.
If i go to:
https://www.office.com/
it demands edge. If I click Continue in edge, it correctly opens in chrome.

URIFailures.log:
2022/08/30 18:05:12 - Invalid URL: -- http://go.microsoft.com/fwlink/p/?LinkId=255142
2022/08/30 18:05:17 - Invalid URL: -- https://www.google.com/?noj=1&nord=1&gws_rd=cr&ei=us&gl=us&hl=en&fg=1
2022/08/30 18:11:31 - Invalid URL: -- https://www.google.com/?noj=1&nord=1&gws_rd=cr&ei=us&gl=us&hl=en&fg=1
2022/08/30 18:12:47 - Invalid URL: -- https://www.google.com/?noj=1&nord=1&gws_rd=cr&ei=us&gl=us&hl=en&fg=1

That's the default bing favorite, and my custom google one (always opens google.com in US english regardless of googles location detection)

### ✔️ Expected Behavior

Favorites should work as normal when clicked inside IE11 on windows 11.

### ❌ Actual Behavior

MSEdgeRedirect flashes in system tray, logs the url as invalid and prevents IE from operating normally.

### Microsoft Windows version

Up to date Stable Windows 11 install (21H2, Build 22000)

**Comment by rcmaehl** [comment]
I haven't been able to reproduce this on Windows 10 but I'll test it out on Windows 11 and see what's occurring.

**Comment by rcmaehl** [comment]
As the Internet Explorer Optional Feature will be disabled come February I'm going to mark this as "wontfix" but I'll leave this open to take a look during the code rewrite for enterprise/prosumer users

**Comment by rcmaehl** [comment]
Was able to reproduce. WIll fix

**Comment by rcmaehl** [comment]
Should be fixed in the latest dev build.

**Comment by Axer128** [comment]
Just tested the nightly:
No longer flashes MSER in the systray, but still doesn't work - just crashes the current tab.
Clicking the favorite a 2nd time sends the url to:
res://ieframe.dll/acr_error.htm#google.com,https://www.google.com/
With error:  
We were unable to return you to google.com.    
Internet Explorer has stopped trying to restore this website. It appears that the website continues to have a problem.  
What you can do:   Go to your home page  
   Try to return to google.com   
    More information  More information  
When a website causes a failure or crash, Internet Explorer attempts to restore the site. It stops after two tries to avoid an endless loop.
 
Clicking it further stacks the url like this:
res://ieframe.dll/acr_error.htm#,res://ieframe.dll/acr_error.htm#google.com,https://www.google.com/

**Comment by micwoj92** [comment]
Is this actually fixed?

**Comment by Axer128** [comment]
No still bugged as explained in OP. Also Internet Explorer was never disabled/removed even in the latest windows 11 release, still launches with -embedding as explained in the OP.

Having it functional is still necessary as a tons of even not that old software requires it for embedding, especially video games.
